import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { NavigationProgress } from '@/components/navigation-progress'
import { Toaster } from 'sonner'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ReactQueryProvider } from '@/components/providers/react-query.provider'
import { DirectionProvider } from '@/components/providers/direction-provider'
import { I18nProvider } from '@/components/providers/i18n.provider'
import '@/styles/index.css'
import { getServerCookie } from '@/lib/cookies/server'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const dir = (await getServerCookie<'ltr' | 'rtl'>('dir')) ?? 'ltr'
  const lang = (await getServerCookie<'en' | 'ar'>('dir')) ?? 'ltr'

  return (
    <html lang={lang} dir={dir}>
      <ReactQueryProvider>
        <ThemeProvider>
          <DirectionProvider>
            <I18nProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <NavigationProgress />
                {children}
                <Toaster duration={5000} />
                {process.env.Mode === 'development' && (
                  <ReactQueryDevtools buttonPosition="bottom-left" />
                )}
              </body>
            </I18nProvider>
          </DirectionProvider>
        </ThemeProvider>
      </ReactQueryProvider>
    </html>
  )
}
